"""empty message

Revision ID: 31016f937759
Revises: f92312ff6286
Create Date: 2020-11-13 15:32:05.862714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31016f937759'
down_revision = 'f92312ff6286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cart', 'size',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('history', 'color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('history', 'size',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('name', table_name='history')
    op.drop_index('card', table_name='transactions')
    op.drop_index('street_address', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('street_address', 'user', ['street_address'], unique=True)
    op.create_index('card', 'transactions', ['card'], unique=True)
    op.create_index('name', 'history', ['name'], unique=True)
    op.alter_column('history', 'size',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('history', 'color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cart', 'size',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cart', 'color',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
